server:
  pool:
    pool-size: 2
    max-pool-size: 4
    keep-alive-time: 5000
  email:
    host: smtp.163.com
    user: wan06051180@163.com
    passwd: lin199105
    debug: false
  send:
    time: 07:00
weather:
  url: https://www.tianqiapi.com/api
  appid: 83423352
  appsecret: 6m1wkvcp
  version: v6
receivers:
  - name: linwl
    email: 2489720745@qq.com
    city-id: 101280800
  - name: yangxz
    email: 742438711@qq.com
    city-id: 101280800
  - name: linjk
    email: 312507683@qq.com
    city-id: 101280800
  - name: linr
    email: lionry0909@163.com
    city-id: 101280101